[https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html
](https://)

In [2]:
import numpy as np

# https://numpy.org/doc/stable/user/basics.broadcasting.html
# https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

# Broadcasting
# Broadcasting is simply a set of rules for applying binary ufuncs 
# (addition, subtraction, multiplication, etc.) on arrays of different sizes.

# preforming a mathematical operation on array and number 
# with numpy array the operation will be preformed on each element contained in the array 
array=np.array([1 , 2, 3])
print('array:' , array)
print('array+5:' ,array+5)


array: [1 2 3]
array+5: [6 7 8]


In [8]:
# preforming any mathematical operation on two arrays with the same size 
# will work with indexes and preform the operation on these arrays 
x=np.array([1 , 2 , 3])
y=np.array([4 , 5 , 6])
print('x:' , x)
print('y:' , y)
print('x+y:' , x+y)

x: [1 2 3]
y: [4 5 6]
x+y: [5 7 9]


In [8]:
# preforming any mathematical operation on two arrays with the 1D array and 2D array

x=np.array([1 , 2, 3])
y=np.ones((4 , 3))

print(f'x dimensions:{x.ndim} , x shape:{x.shape} ')
print(f'y dimensions:{y.ndim} , y shape:{y.shape} ')

print('x:\n' , x)
print('y:\n' , y)
print('x+y:\n' , x+y)


# x dimensions:1 , x shape:(N,) 
# y dimensions:2 , y shape:(M, N)

# the number of elements in the 1D array have to be equal to number of columns in the 2D array 
# and the operation is preformed to each row individually 


x dimensions:1 , x shape:(3,) 
y dimensions:2 , y shape:(4, 3) 
x:
 [1 2 3]
y:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
x+y:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [9]:
x=np.arange(0 , 3)
y=np.arange(0 , 3).reshape(3 , 1)

print(f'x dimensions:{x.ndim} , x shape:{x.shape} ')
print(f'y dimensions:{y.ndim} , y shape:{y.shape} ')

print('x:\n' , x)
print('y:\n' , y)
print('x+y:\n' , x+y)

# how it works 

#    0  1  2 
# 0  0  1  2
# 1  1  2  3 
# 2  2  3  4



x dimensions:1 , x shape:(3,) 
y dimensions:2 , y shape:(3, 1) 
x:
 [0 1 2]
y:
 [[0]
 [1]
 [2]]
x+y:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

1) Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Ex:
x.shape = (2,3)  , y.shape=(3,)
it will become 
x.shape = (2,3)  , y.shape=(1,3)


2) Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Ex:
x.shape = (2,3)  , y.shape=(1,3)
it will become 
x.shape = (2,3)  , y.shape=(2,3)


3) Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Ex:
it x.shape = (2,3)  , y.shape=(1,3) become x.shape = (2,3)  , y.shape=(2,3)
otherwise it will raise an error 



In [12]:
# Broadcasting example 1
x = np.ones((2, 3))
y = np.arange(3)

# x dimensions:2 , x shape:(2, 3) 
# y dimensions:1 , y shape:(3,) 
print(f'x dimensions:{x.ndim} , x shape:{x.shape} ')
print(f'y dimensions:{y.ndim} , y shape:{y.shape} ' , end='\n\n')

# We see by rule 1 that the array y has fewer dimensions, so we pad it on the left with ones
# x dimensions:2 , x shape:(2, 3) 
# y dimensions:2 , y shape:(1, 3) 

# By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match
# x dimensions:2 , x shape:(2, 3) 
# y dimensions:2 , y shape:(2, 3)

# then we can preform the operation on them 
print('x:\n' , x)
print('y:\n' , y)
print('x+y:\n' , x+y)


x dimensions:2 , x shape:(2, 3) 
y dimensions:1 , y shape:(3,) 

x:
 [[1. 1. 1.]
 [1. 1. 1.]]
y:
 [0 1 2]
x+y:
 [[1. 2. 3.]
 [1. 2. 3.]]


In [14]:
# Broadcasting example 2
x = np.arange(3).reshape((3, 1))
y = np.arange(3)

# x dimensions:2 , x shape:(3, 1) 
# y dimensions:1 , y shape:(3,) 
print(f'x dimensions:{x.ndim} , x shape:{x.shape} ')
print(f'y dimensions:{y.ndim} , y shape:{y.shape} ' , end='\n\n')

# Rule 1 says we must pad the shape of y with ones
# x dimensions:2 , x shape:(3, 1) 
# y dimensions:2 , y shape:(1, 3)

#And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array
# x dimensions:2 , x shape:(3, 3) 
# y dimensions:2 , y shape:(3, 3)

#Because the result matches, these shapes are compatible. We can see this here
print('x:\n' , x)
print('y:\n' , y)
print('x+y:\n' , x+y)



x dimensions:2 , x shape:(3, 1) 
y dimensions:1 , y shape:(3,) 

x:
 [[0]
 [1]
 [2]]
y:
 [0 1 2]
x+y:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [16]:
# Broadcasting example 2
x = np.ones((3, 2))
y = np.arange(3)

# x dimensions:2 , x shape:(3, 2) 
# y dimensions:1 , y shape:(3,) 


print(f'x dimensions:{x.ndim} , x shape:{x.shape} ')
print(f'y dimensions:{y.ndim} , y shape:{y.shape} ' , end='\n\n')

# rule 1 tells us that we must pad the shape of y with ones
# x dimensions:2 , x shape:(3, 2) 
# y dimensions:2 , y shape:(1, 3)

# By rule 2, the first dimension of y is stretched to match that of x
# x dimensions:2 , x shape:(3, 2) 
# y dimensions:2 , y shape:(3, 3)

# Now we hit rule 3–the final shapes do not match, so these two arrays are incompatible,
# as we can observe by attempting this operation
print('x:\n' , x)
print('y:\n' , y)
print('x+y:\n' , x+y)

x dimensions:2 , x shape:(3, 2) 
y dimensions:1 , y shape:(3,) 

x:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
y:
 [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

![alt text](pictures/broadcasting.png)