[https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html](https://)


In [3]:
import numpy as np
# slicing an one dimensional array and get subarray
# start:end:step
# note that:The ending is excluded
array=np.arange(0 , 10)
print(array)
print('*'*21)

print(array[0:5])
print(array[:9:2])

[0 1 2 3 4 5 6 7 8 9]
*********************
[0 1 2 3 4]
[0 2 4 6 8]


In [4]:


# slicing an multidimensional array and get subarray
# lets first create an array 
array=np.array([[1 , 2 , 3 , 4] , [5 , 6, 7 , 8] , [9 , 10 , 11 , 12]])
print(array)
# this is a 2D array that have (3 , 4) shape and 12 elements inside it 
print('*' * 15)

# you can slice rows and columns in the same way 
# start:end:step
# note that:The ending is excluded
# note that dont use array[row][column] instead array[row,column] when you are working with slicing 

# so if i want to get the 6 , 7 , 10 , 11 

print(array[1: , 1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
***************
[[ 6  7]
 [10 11]]


In [5]:
# accessing rows and columns
print(array[: , 0]) # specific column
print(array[0 , :]) # specific row

[1 5 9]
[1 2 3 4]
