[https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html
](https://)

In [1]:
import numpy as np 
import pandas as pd

### **Data Frame**
##### from pandas Series 

In [5]:
population_dic={ 'Baghdad' : 7655695,
                'Tunis':633894,
                'Algeria' :3569126,
                'Riyadh' :1618935,
                'Cairo' : 9568232
                }

population=pd.Series(population_dic)
print('population Series\n:' , population ,  end='\n\n')

area_dict={ 'Baghdad' : 204,
            'Riyadh':1973,
            'Tunis': 212, 
            'Algeria': 1190,
            'Cairo':3085
            }
area=pd.Series(area_dict)
print('area Series:\n'  , area , end='\n\n')


data_frame=pd.DataFrame({'population':population , 'area':area})
print('data Frame form Series:\n' ,data_frame)

population Series
: Baghdad    7655695
Tunis       633894
Algeria    3569126
Riyadh     1618935
Cairo      9568232
dtype: int64

area Series:
 Baghdad     204
Riyadh     1973
Tunis       212
Algeria    1190
Cairo      3085
dtype: int64

data Frame form Series:
          population  area
Algeria     3569126  1190
Baghdad     7655695   204
Cairo       9568232  3085
Riyadh      1618935  1973
Tunis        633894   212


##### from python dictionary  

In [9]:
data_frame=pd.DataFrame({'population':[7655695,633894,3569126,1618935,9568232 ] ,
                        'area':[204,1973,212,1190,3085]} , 
                        index=['Baghdad','Riyadh','Tunis','Algeria','Cairo'])
print('data Frame form dictionary:\n' ,data_frame)

data Frame form dictionary:
          population  area
Baghdad     7655695   204
Riyadh       633894  1973
Tunis       3569126   212
Algeria     1618935  1190
Cairo       9568232  3085


#### some important functions 

In [16]:
print('indexes:' , data_frame.index)
print('columns:' , data_frame.columns)
print('specific data in some column:\n' , data_frame['area'])
print('specific value some column:' , data_frame['area']['Cairo'])

indexes: Index(['Baghdad', 'Riyadh', 'Tunis', 'Algeria', 'Cairo'], dtype='object')
columns: Index(['population', 'area'], dtype='object')
specific data in some column:
 Baghdad     204
Riyadh     1973
Tunis       212
Algeria    1190
Cairo      3085
Name: area, dtype: int64
specific value some column: 3085


#### From a Single Series Object

In [22]:
area_dict={ 'Baghdad' : 204,
            'Riyadh':1973,
            'Tunis': 212, 
            'Algeria': 1190,
            'Cairo':3085
            }
area=pd.Series(area_dict)
print('area Series:\n'  , area)
print('area type:'  , type(area))

data_frame=pd.DataFrame(area , columns=['area'])
#data_frame=pd.DataFrame({'area':area}) same as pd.DataFrame(area , columns=['area'])
print('data frame:\n' , data_frame)

area Series:
 Baghdad     204
Riyadh     1973
Tunis       212
Algeria    1190
Cairo      3085
dtype: int64
area type: <class 'pandas.core.series.Series'>
data frame:
          area
Baghdad   204
Riyadh   1973
Tunis     212
Algeria  1190
Cairo    3085


##### from a list of dictionarys  

In [31]:
data=[ {'a':1 , 'b':2} , {'a':3 , 'b':4} , {'a':5 , 'b':6} ]
print('data frame:\n', pd.DataFrame(data , index=['first' , 'second' , 'third']) , end='\n\n')
data=[ {'a':1 , 'b':2} , {'c':3 , 'd':4}]
print('data frame:\n', pd.DataFrame(data , index=['first ' , 'second ']))
#when some keys are missing nan will appear 

data frame:
         a  b
first   1  2
second  3  4
third   5  6

data frame:
            a    b    c    d
first    1.0  2.0  NaN  NaN
second   NaN  NaN  3.0  4.0


#### from two dimensional numpy array 

In [42]:
np.random.seed(42)
array=np.random.randint(20 , 50 , size=(10 , 3))
print(array)
indexes=['One', 'Two', 'Three', 'Four', 'Five',  'Six', 'Seven', 'Eight', 'Nine', 'Ten']
data_frame=pd.DataFrame(array , columns=['first' , 'second' , 'third'] , 
                        index=[name for name in indexes])
print(data_frame)

[[26 39 48]
 [34 30 27]
 [48 40 26]
 [45 38 42]
 [30 30 43]
 [40 23 27]
 [43 22 41]
 [40 21 43]
 [31 49 25]
 [21 47 40]]
       first  second  third
One       26      39     48
Two       34      30     27
Three     48      40     26
Four      45      38     42
Five      30      30     43
Six       40      23     27
Seven     43      22     41
Eight     40      21     43
Nine      31      49     25
Ten       21      47     40
