[https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html
](https://)

In [16]:
import numpy as np
# https://www.kaggle.com/code/orhansertkaya/numpy-tutorial-for-beginners#Aggregations:-Min,-Max,-and-Everything-in-Between
# sum with 1D 
array=np.arange(10)
print(np.sum(array))

45


In [19]:

# sum with 2D
array = np.arange(0 , 100).reshape(10 , 10)
print( 'array:\n', array , end='\n\n')

print('sum of rows:',np.sum(array , axis=0)) # axis=0 will sum along rows  
print( 'sum of columns:', np.sum(array , axis=1 , keepdims=True)) # axis=1 will sum along columns

# keepdims have a default value False 
# and as it name suggests this parameter assigned to True will keep the dimensions of the array as it is


array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

sum of rows: [450 460 470 480 490 500 510 520 530 540]
sum of columns: [ 45 145 245 345 445 545 645 745 845 945]


In [18]:
# minimum and maximum 
print('maximum:',np.max(array))
print('minimum:' ,np.min(array))

maximum: 99
minimum: 0


![alt text](<pictures/Aggregation Functions .PNG>)