[https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html
](https://)

In [3]:
import numpy as np

# array reshape 

# lets consider this array 

# [0, 1, 2, 3, 4, 5, 6, 7, 8, ,9, 10 , 11] with 12 elements 

# you can reshape it to 

# [[0, 1, 2, 3]
# [4, 5, 6, 7]
# [8, 9, 10, 11]]

# or 

# [[0, 1, 2]
# [3, 4, 5]
# [6, 7, 8]
# [9, 10, 11]]


In [18]:
array = np.arange(0 , 12)
print(array)

#lets reshape it 
print('*'*37)
reshaped_array=array.reshape((3 , 4))
print(reshaped_array)

#-----------------------------------------------
print('*'*37)
#alternative way 
array = np.arange(0 , 12).reshape((3 , 4))
print(array)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
*************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
# you must take in to consideration the size of the array before you reshape it 


array=np.arange(0 , 100).reshape((10 , 10))
print("array size:" , array.size) # you can Reshape it with 10x10 array that contain 100 element 
print(array)

array size: 100
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [31]:
# row vector 
array=np.array([1 , 2, 3])
print(array.shape) # and this is an array with one row that contain 3 elements
print(array.ndim)
print('*'*20)
# to get a row vector just do the following
print(array.reshape((1 , 3)).shape)
print(array.reshape((3 , 1)).ndim)
print('*'*20)
# to get a columns vector just do the following
print(array.reshape((3 , 1)).shape)
print(array.reshape((3 , 1)).ndim)



(3,)
1
********************
(1, 3)
2
********************
(3, 1)
2
