[https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html
](https://)

In [4]:
import numpy as np

# Shallow copy

# first of all lets create an array
array=np.array([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8] , [9, 10 , 11 , 12]])
print(array)
print('*'*15)
# and then lets take sub array from this array
sub_array=array[:2 ,:2]
print(sub_array)

# the sub array is in the same location of the original array 
# so if you change any thing in the sub array it will be changed in the original one 
print('*'*15)
sub_array[0,0]=99
print(sub_array)
print(array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
***************
[[1 2]
 [5 6]]
***************
[[99  2]
 [ 5  6]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
array_1=np.array([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8] , [9, 10 , 11 , 12]])
array_2=array_1
print(array_2)
array_1[0 , 0]=100
print(array_2)
# as you can see in this way you will take a shallow copy of the array not a deep copy 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


A shallow copy creates a new array, but it does not create new copies of the elements within the array. Instead, it points to the same elements as the original array. A deep copy, on the other hand, creates a completely independent copy of both the array and its data. It does not share any data with the original array.

In [10]:
# Deep copy 
# first of all lets create an array
array=np.array([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8] , [9, 10 , 11 , 12]])
print(array)
print('*'*15)
# by using copy function it will take a real copy of the array that is completely independent
# and dose not reflect the original copy 
sub_array=array[:2 , :2].copy()
# lets test it and as you can see the array changed with no effects on the sub array
array[0 , 0]=99
print(sub_array , end='\n\n')
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
***************
[[1 2]
 [5 6]]

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
