[https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html](https://)


In [5]:
import numpy as np
#lets first create an array 
array=np.zeros((3 , 4) , dtype=int)
print(array)

# some important attributes to get informations about our array
print(f'array dimensions:{array.ndim}') # dimensions of the array
print(f'array shape:{array.shape}') # shape (rows , columns) or the array
print(f'array size:{array.size}') # number or elements in the array


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
array dimensions:2
array shape:(3, 4)
array size:12


In [19]:
#array indexing 
array=np.array([[1 , 2 , 3 , 4] , [5 , 6, 7 , 8] , [9 , 10 , 11 , 12]])
print(array)
print(f'array dimensions:{array.ndim}') 
print(f'array shape:{array.shape}')
print(f'array size:{array.size}') 
print('*' * 20)

#indexing in the arrays start from 0
print(array[0][0]) # you can also use array[0 , 0] and it is the same shit

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array dimensions:2
array shape:(3, 4)
array size:12
********************
1
