[https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html
](https://)

In [7]:
import numpy as np

# Array concatenation in 1D array 
x=np.array([1 , 2, 3])
y=np.array([4 , 5, 6])
print('array x:' , x)
print('array y:' , y)
print('array x concatenated with y:', np.concatenate([x , y]))
z=[99 , 99 , 99] # python list 
print('array x and concatenated with list z:', np.concatenate([x , y , z]))


array x: [1 2 3]
array y: [4 5 6]
array x concatenated with y: [1 2 3 4 5 6]
array x and concatenated with list z: [ 1  2  3  4  5  6 99 99 99]


In [23]:
# Array concatenation in 2D array

x=np.full((2 , 3) , 1)
y=np.full((2 , 3) , 9)

print('array x:\n', x , end='\n\n')
print('array y:\n', y , end='\n\n')

# to concatenate arrays in 2D you have to use axis parameter to specify exactly how to concatenate your arrays
# axis = 0 that mean you want to concatenate along the Rows 
# axis = 1 that mean you want to concatenate along the columns 

print(f'along Rows:{x.shape} + {y.shape} = (4 , 3)')
print('along Rows:\n' , np.concatenate([x , y] , axis=0) ,end='\n\n')

print(f'along columns:{x.shape} + {y.shape} = (2 , 6)')
print('along columns:\n' , np.concatenate([x , y] , axis=1) ,end='\n\n')

# note that if you want to concatenate along rows the two arrays must have the same number columns
# note that if you want to concatenate along columns the two arrays must have the same number rows

array x:
 [[1 1 1]
 [1 1 1]]

array y:
 [[9 9 9]
 [9 9 9]]

along Rows:(2, 3) + (2, 3) = (4 , 3)
along Rows:
 [[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]

along columns:(2, 3) + (2, 3) = (2 , 6)
along columns:
 [[1 1 1 9 9 9]
 [1 1 1 9 9 9]]



In [30]:
x=np.array([1 , 2, 3])
y=np.array([[1 , 2 ,3] , [4 , 5, 6]])
# as you can see x is 1D array and y is 2D array so the concatenate method can't concatenate them 
# you want to reshape the x array and change it to 2D array 
print('x dimensions:', x.ndim)
print('x shape:', x.shape)
print('y dimensions:', y.ndim)
print('y shape:', y.shape)
x=x.reshape((1 , 3))
print('x dimensions after reshape:', x.ndim)
print('x shape after reshape:', x.shape)

print(np.concatenate([x , y] , axis=0))


x dimensions: 1
x shape: (3,)
y dimensions: 2
y shape: (2, 3)
x dimensions after reshape: 2
x shape after reshape: (1, 3)
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [31]:
# alternative way vertical stack
x=np.array([1 , 2, 3])
y=np.array([[1 , 2 ,3] , [4 , 5, 6]])
print(np.vstack([x , y]))

[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [32]:
# alternative way vertical stack
x=np.array([[99],
            [99]])
y=np.array([[1 , 2 ,3] , [4 , 5, 6]])
print(np.hstack([x , y]))

[[99  1  2  3]
 [99  4  5  6]]
