### **Fancy Indexing**

[https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html
](https://)

In [3]:
import numpy as np
rand= np.random.RandomState(42)
array=np.random.randint(100 , size=10)
print(array)

[19 45 22 88 47 96 20 80 29 86]


### 1D Fancy indexing 

In [10]:
print('array:', array)
# the old way of indexing slicing 
print('slicing:',array[2:5])
# but this way will get you the elements linearly from the array

# good way but not enough alternative way using list
ind=[4 , 2 ,8]
print('Fancy Indexing:', array[ind]) # print(array[[4 , 2 ,8]])

# and you can use indexing in 2D array not just list 
ind=np.array([[8,2],[7,1]])
print('Fancy Indexing:\n', array[ind])





array: [19 45 22 88 47 96 20 80 29 86]
slicing: [22 88 47]
Fancy Indexing: [47 22 29]
Fancy Indexing:
 [[29 22]
 [80 45]]


### 2D Fancy indexing 

In [16]:
array=np.arange(16).reshape((4, 4))
print('array:\n' , array)

row=np.array([0, 1, 2, 3])
col=np.array([0, 1, 2, 3])

print('Fancy Indexing:\n', array[row , col])

array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Fancy Indexing:
 [ 0  5 10 15]


### Combined Indexing

In [37]:
# the old indexing way with Fancy indexing 

np.random.seed(42)
array=np.random.randint(100 , size=(16))
print('array:' , array)

print('indexing:',array[2]) # old way of indexing in 1D
ind=np.array([4 , 5 ,3 ,9])
print('Fancy indexing:' , array[ind] , end='\n\n') # Fancy indexing in 1D

# Combined Indexing in 2D
array=np.random.randint(100 , size=(16) , dtype=int).reshape(4 , 4)
print('array:\n' , array)

# array[row , col]
# you can use slicing and the indexing with Fancy indexing 
# rows and columns and manipulate your array

print('Combined Indexing:' , array[2 ,[0 , 3 ,1 ,2]])
# in this line of code it will take the second row and get the indexes 0 , 3 , 1 , 2 respectively

array: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52]
indexing: 14
Fancy indexing: [60 20 71 74]

array:
 [[ 1 87 29 37]
 [ 1 63 59 20]
 [32 75 57 21]
 [88 48 90 58]]
Combined Indexing: [32 21 75 57]
