[https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html](https://)

In [23]:
import numpy as np

# Creating numpy array from python list
# in numpy array the array can't handel more than one data type 
array=np.array([1 , 2 , 3 , 4])
print(array)


[1 2 3 4]


In [24]:
array=np.array([1 , 2 , 3 , 4.4])
print(array) 
# as you can see numpy change the data type for each element of the array
  

[1.  2.  3.  4.4]


In [25]:
# and you can explicitly define your data type by using dtype= parameter 
array=np.array([1 , 2 , 3 , 4.4] , dtype='int64')
print(array) 


[1 2 3 4]


In [26]:
# Creating numpy array from scratch zeros method 

array=np.zeros(10 , dtype=int)
print(array)

[0 0 0 0 0 0 0 0 0 0]


In [27]:
# ones method 
#         (rows , columns)
array=np.ones((3 , 5) , dtype=int)
print(array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [35]:
# you can also create array filled in whatever you wish using full method 

array=np.full((3 , 5) , 9.9)
print(array)

[[9.9 9.9 9.9 9.9 9.9]
 [9.9 9.9 9.9 9.9 9.9]
 [9.9 9.9 9.9 9.9 9.9]]


In [41]:
# creating array with filled with a linear sequence
array=np.arange(0 , 10)# The ending is excluded
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
# stating with 0 , ending at 20 , stepping by 2
array=np.arange(0 , 20 , 2) # The ending is excluded
print(array) 

[ 0  2  4  6  8 10 12 14 16 18]


In [44]:
# create a 3x3 array of uniformly distributed
# random values between 0 and 1 
array=np.random.random((3 , 3))
print(array)

[[0.9959571  0.17528743 0.77648719]
 [0.97136783 0.64663249 0.13553579]
 [0.59901174 0.57143478 0.98808572]]


In [46]:
# create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1  
#np.random.normal(loc(Mean) , scale(Standard deviation) , size)
array=np.random.normal(0 , 1 , (3 , 3))
print(array)

[[-0.20043145  0.49855218  0.62879739]
 [-0.37156346 -1.65387872 -0.23832779]
 [ 0.57763456  0.61905244 -0.58470159]]


In [50]:
# create a 3x3 array or random integers in the interval [a , b)
array=np.random.randint(0 , 100 , (3 , 4))
print(array)

[[59 57  9 90]
 [31 85 77 87]
 [28 60 61 68]]


In [52]:
# create a 3x3 identity array
array=np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# creating an uninitialized array of three integers
# the value will be whatever happen to exist at that 
# memory location 
array=np.empty((3,4))
print(array)

[[4.67296746e-307 1.69121096e-306 2.67022274e-307 2.67019320e-306]
 [1.42413555e-306 1.78019082e-306 1.37959740e-306 6.23057349e-307]
 [1.42419530e-306 9.45739574e-308 1.95813426e-306 8.45603441e-307]]
