[https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html
](https://)

In [9]:
import numpy as np
np.random.seed(42)
x=np.array([3 , 4, 5, 6  , 4 ,8])
y=np.random.randint(-3 , 10 , size=20).reshape(4 , 5)
print('x:\n' , x)
print('y:\n', y)

x:
 [3 4 5 6 4 8]
y:
 [[ 3  0  9  7  4]
 [ 9  1  3  6 -1]
 [ 3  7  7  4  1]
 [ 0  4  4 -1  2]]


#### np.sort()

In [10]:

print('sorted array x:',np.sort(x))
#Recap: axis=0 will sort along Rows
#Recap: axis=1 will sort along columns
print('(ascending) sorted array y along rows:\n' , np.sort(y , axis=0))
print('(ascending) sorted array y along columns:\n' , np.sort(y , axis=1))


# note that: the default argument of axis in sort method is -1 
# -1 means that the sort will be along the last axis that our array have 
# for example if our array is 3D the axises are 0 , 1 , 2 and the -1 from them is 2 
# if our array is 5D the axises are 0 , 1 , 2 , 3 , 4 and the -1 from them is 4 


# note that the sort function preform ascending sort to get descending you have to reverse the array
print('(descending) sorted array y along rows:\n' , np.sort(y , axis=0)[::-1])
print('(descending) sorted array y along columns:\n' , np.sort(y , axis=1)[::-1])

sorted array x: [3 4 4 5 6 8]
(ascending) sorted array y along rows:
 [[ 0  0  3 -1 -1]
 [ 3  1  4  4  1]
 [ 3  4  7  6  2]
 [ 9  7  9  7  4]]
(ascending) sorted array y along columns:
 [[ 0  3  4  7  9]
 [-1  1  3  6  9]
 [ 1  3  4  7  7]
 [-1  0  2  4  4]]
(descending) sorted array y along rows:
 [[ 9  7  9  7  4]
 [ 3  4  7  6  2]
 [ 3  1  4  4  1]
 [ 0  0  3 -1 -1]]
(descending) sorted array y along columns:
 [[-1  0  2  4  4]
 [ 1  3  4  7  7]
 [-1  1  3  6  9]
 [ 0  3  4  7  9]]


#### np.argsort()

In [11]:
# the one and the only difference between sort and argsort that 
# sort function will return sorted array with values 
# argsort function will return sorted array with indexes 

print('sorted array x:',np.argsort(x))
print('(ascending) sorted array y along rows:\n' , np.argsort(y , axis=0))
print('(ascending) sorted array y along columns:\n' , np.argsort(y , axis=1))

sorted array x: [0 1 4 2 3 5]
(ascending) sorted array y along rows:
 [[3 0 1 3 1]
 [0 1 3 2 2]
 [2 3 2 1 3]
 [1 2 0 0 0]]
(ascending) sorted array y along columns:
 [[1 0 4 3 2]
 [4 1 2 3 0]
 [4 0 3 1 2]
 [3 0 4 1 2]]


#### np.any() or ∃  

In [12]:
x=np.array([True , False , True , False , False])
y=np.array([[True , False , True]
            ,[True , False , True]])
print(np.any(x)) # at least one True value in the array x
print(np.any(y , axis=0 , keepdims=True)) # along Rows 
print(np.any(y , axis=1)) # along columns 


True
[[ True False  True]]
[ True  True]


#### np.all() or ∀

In [13]:
print(np.all(x)) # for all values in x must be True  
print(np.all(y , axis=0)) # along Rows 
print(np.all(y , axis=1)) # along columns 

False
[ True False  True]
[False False]


#### numpy.where()

In [18]:
array=np.array([5 , 6 , -1 , -6 , 8 , 10 , -20])
# np.where() is as same as the ternary operator in c++ language 
# c++ => (condition)?True_case:False_case 
# python => np.where(condition,True_case,False_case)
# simply it will replace the value from the array by the True_case if the value is True according to the condition
# otherwise it will replace the value from the array by the False_case
print(np.where(array < 0 , 0 , array))

[ 5  6  0  0  8 10  0]


#### numpy.isnan()

In [35]:
x = np.array([1,2,3,np.nan,67])
print('array x:',x)
print('array x mean:' , np.mean(x))
# some data can have nan it is just undefined index and have no value 
# it can arise problems if you want to calculate a mean the value will be nan 

# isnan() simply is a method that return a boolean array with True if there is an nan in your data 
print('isnan x:', np.isnan(x) , end='\n\n')


y=np.array([[np.nan , 1 , 2 ,3]
            ,[4 ,5 , np.nan , 7]
            ,[8 , 9 , 10 , np.nan]])
print('array y:\n',y)

print('isnan y:\n', np.isnan(y)) #there is no axis parameter here 

# if you want to check rows or columns you can use np.any() method 
print( 'isnan along Rows:\n', np.any(np.isnan(y) , axis=0 ,keepdims=True)) # along rows
print('isnan along Rows:\n', np.any(np.isnan(y) , axis=1 ,keepdims=True)) # along rows




array x: [ 1.  2.  3. nan 67.]
array x mean: nan
isnan x: [False False False  True False]

array y:
 [[nan  1.  2.  3.]
 [ 4.  5. nan  7.]
 [ 8.  9. 10. nan]]
isnan y:
 [[ True False False False]
 [False False  True False]
 [False False False  True]]
isnan along Rows:
 [[ True False  True  True]]
isnan along Rows:
 [[ True]
 [ True]
 [ True]]


#### np.savetxt()

In [41]:
array=np.random.randint(-10 , 10 ,size=1000 , dtype=int).reshape(100 , 10)
print(array)
np.savetxt('Ex_data.csv' , array , delimiter=',')

[[  6 -10 -10  -6   1  -5  -5   6   2  -3]
 [  1   4   8   9   6  -2   7  -9   0   9]
 [  6   7   4  -4   5 -10   7  -3  -4  -9]
 [  1   5  -2   9   0   4  -8   2   2  -9]
 [ -5  -5   1  -7  -6  -3  -5  -8  -3   8]
 [  0   7  -1   9   1   9  -3   8   5   7]
 [ -2  -7  -2  -9  -2  -2   7   0   2  -5]
 [ -2   5  -7  -9  -4   4  -5   0   9   6]
 [ -7   8  -4   0   2  -8   3  -9   7  -6]
 [  2   2   3   1   2   7   2  -7  -1  -6]
 [  7  -3   3  -9  -3   5  -4  -8  -7  -4]
 [ -7  -2   6   6   9   3   3   2  -7   2]
 [  6   4   7   0  -7   9   0  -1   2  -3]
 [  2  -2 -10 -10   4  -7   9 -10   1   0]
 [  8   4  -1 -10  -8   3   4 -10  -1 -10]
 [  4  -8   9   1   8   5  -3   3   7 -10]
 [ -9   1   6  -9   6  -4  -5  -5  -3  -6]
 [  4  -4  -8  -1  -8   3  -8 -10 -10   8]
 [ -7  -9   0   1   2   5   5   8   9   9]
 [ -2   5  -4   2  -7   2  -3  -9  -4   0]
 [  6   3   2   4  -2  -8   2   2  -2   7]
 [ -6   0  -9   6   9  -7   7   9  -3   8]
 [  1   0   5  -6  -8   1   4   5   2  -4]
 [  4  -8  