In [6]:
import numpy as np
# splitting an array is easy using split method 
# split a 1D array

array=np.arange(0 , 12)
print(array)
x1,x2,x3=np.split(array , [4 , 8]) # N splits will lead to N+1 sub array
print('x1:', x1)
print('x2:', x2)
print('x3:', x3)
# split method in 1D work with the indexes 
# np.split(array , [N , M])
# it starts with 0 until it reach N-1 thats the first cut 
# the second cut will be from N to M-1
# the third cut will start from M to the end of the array 
# no need to specify start pint 0 , by default  it is 0 


[ 0  1  2  3  4  5  6  7  8  9 10 11]
x1: [0 1 2 3]
x2: [4 5 6 7]
x3: [ 8  9 10 11]


In [19]:
# split a 2D array
array = np.arange(0 , 16).reshape(4 , 4)
print( 'array:\n', array , end='\n\n')

# there are two ways to split 2D array 

# vertical split (along rows)
# np.split(array , [N , M])
# it starts with 0 until it reach N-1 thats the first cut 
# the second cut will be from N to M-1
# the third cut will start from M to the end of the array 
# no need to specify start pint 0 , by default  it is 0 
print('vertical split:')
upper , lower = np.vsplit(array , [2])
print('upper sub array:\n',   upper  )
print('lower sub array:\n',   lower  , end='\n\n')

# horizontal split (along columns)
print('horizontal split:')
right , left = np.hsplit(array , [ 2 ]) 
print('right sub array:\n',  right )
print('left sub array:\n',  left)


array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

vertical split:
upper sub array:
 [[0 1 2 3]
 [4 5 6 7]]
lower sub array:
 [[ 8  9 10 11]
 [12 13 14 15]]

horizontal split:
right sub array:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
left sub array:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
